import {
  LucideIcon,
  Apple,
  Archive,
  Baby,
  Banana,
  Beef,
  Beer,
  Bone,
  Book,
  Box,
  Brush,
  CakeSlice,
  Camera,
  Candy,
  Car,
  Carrot,
  Cat,
  Cherry,
  Citrus,
  Clover,
  Coconut,
  Coffee,
  Computer,
  Container,
  CookingPot,
  Cookie,
  Croissant,
  Cucumber,
  CupSoda,
  Dog,
  Droplets,
  Drumstick,
  Egg,
  Fish,
  Flame,
  Flower,
  Gift,
  GlassWater,
  Grape,
  Ham,
  HandSoap,
  Heart,
  Home,
  IceCream,
  Key,
  Lamp,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  Lollipop,
  Microwave,
  Milk,
  Moon,
  Muffin,
  Nut,
  Package,
  Paintbrush,
  PawPrint,
  Pen,
  Pepper,
  PersonStanding,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plus,
  Popcorn,
  Potato,
  Rabbit,
  Recycle,
  Rocket,
  Sandwich,
  Scissors,
  Shirt,
  ShowerHead,
  Shrimp,
  Snowflake,
  Soup,
  Sparkles,
  Speaker,
  Sponge,
  Sprout,
  Store,
  Sun,
  Syringe,
  Ticket,
  ToyBrick,
  Trash2,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Utensils,
  Vegan,
  Wallet,
  WashingMachine,
  Watch,
  Wheat,
  Wine,
  Wrench,
  Zap,
  ShoppingBasket,
  ShoppingCart,
} from 'lucide-react';

export const supermarketIcons: { [key: string]: LucideIcon } = {
  store: Store,
  zap: Zap,
  clover: Clover,
  carrot: Carrot,
  apple: Apple,
  archive: Archive,
  baby: Baby,
  banana: Banana,
  beef: Beef,
  beer: Beer,
  bone: Bone,
  book: Book,
  box: Box,
  brush: Brush,
  'cake-slice': CakeSlice,
  camera: Camera,
  candy: Candy,
  car: Car,
  cat: Cat,
  cherry: Cherry,
  citrus: Citrus,
  coconut: Coconut,
  coffee: Coffee,
  computer: Computer,
  container: Container,
  'cooking-pot': CookingPot,
  cookie: Cookie,
  croissant: Croissant,
  cucumber: Cucumber,
  'cup-soda': CupSoda,
  dog: Dog,
  droplets: Droplets,
  drumstick: Drumstick,
  egg: Egg,
  fish: Fish,
  flame: Flame,
  flower: Flower,
  gift: Gift,
  'glass-water': GlassWater,
  grape: Grape,
  ham: Ham,
  'hand-soap': HandSoap,
  heart: Heart,
  home: Home,
  'ice-cream': IceCream,
  key: Key,
  lamp: Lamp,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  lollipop: Lollipop,
  microwave: Microwave,
  milk: Milk,
  moon: Moon,
  muffin: Muffin,
  nut: Nut,
  package: Package,
  paintbrush: Paintbrush,
  'paw-print': PawPrint,
  pen: Pen,
  pepper: Pepper,
  'person-standing': PersonStanding,
  phone: Phone,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plus: Plus,
  popcorn: Popcorn,
  potato: Potato,
  rabbit: Rabbit,
  recycle: Recycle,
  rocket: Rocket,
  sandwich: Sandwich,
  scissors: Scissors,
  shirt: Shirt,
  'shower-head': ShowerHead,
  shrimp: Shrimp,
  snowflake: Snowflake,
  soup: Soup,
  sparkles: Sparkles,
  speaker: Speaker,
  sponge: Sponge,
  sprout: Sprout,
  sun: Sun,
  syringe: Syringe,
  ticket: Ticket,
  'toy-brick': ToyBrick,
  'trash-2': Trash2,
  'tree-pine': TreePine,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  utensils: Utensils,
  vegan: Vegan,
  wallet: Wallet,
  'washing-machine': WashingMachine,
  watch: Watch,
  wheat: Wheat,
  wine: Wine,
  wrench: Wrench,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
};

export const availableSupermarketIcons = Object.keys(supermarketIcons);