import {
  LucideIcon,
  AirVent,
  AlarmClock,
  Apple,
  Archive,
  Armchair,
  Baby,
  Banana,
  Bath,
  Bean,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  Bird,
  Blinds,
  Bone,
  Book,
  Bot,
  Box,
  Brain,
  Brush,
  Bucket,
  Bug,
  Bus,
  Butterfly,
  Cabbage,
  CakeSlice,
  Camera,
  Camel,
  Candy,
  CandyCane,
  Car,
  Carpet,
  Carrot,
  Cat,
  Chair,
  Cheese,
  Cherry,
  Citrus,
  Clover,
  CoatHanger,
  Coconut,
  Coffee,
  Cog,
  Computer,
  Container,
  CookingPot,
  Cookie,
  Crane,
  Croissant,
  Cucumber,
  CupSoda,
  Curtains,
  Deer,
  Desk,
  Dessert,
  Dog,
  Dolphin,
  DoorClosed,
  DoorOpen,
  Dove,
  Drill,
  Droplets,
  Drumstick,
  Egg,
  EggFried,
  Fan,
  Feather,
  Fence,
  FireExtinguisher,
  Fish,
  FishSymbol,
  Flag,
  Flame,
  Flashlight,
  Flower,
  Flower2,
  Forklift,
  Fox,
  Frog,
  FryingPan,
  Gamepad,
  Gauge,
  Gem,
  Gift,
  GlassWater,
  Grape,
  Ham,
  Hammer,
  HandSoap,
  Headphones,
  Heart,
  Home,
  Horse,
  IceCream,
  IceCream2,
  Iron,
  Keyboard,
  Key,
  Ladder,
  Ladybug,
  Lamp,
  Laptop,
  Leaf,
  Lettuce,
  Library,
  Lightbulb,
  Lock,
  Lollipop,
  Mail,
  Map,
  Martini,
  Microwave,
  Milk,
  Monkey,
  Moon,
  Mop,
  Mouse,
  Muffin,
  Notebook,
  Nut,
  Owl,
  Package,
  PaintRoller,
  Paintbrush,
  Paperclip,
  ParkingCircle,
  PawPrint,
  Pen,
  Pepper,
  PersonStanding,
  Phone,
  PictureInPicture,
  PieChart,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plug,
  PlugZap,
  Plus,
  Popcorn,
  Potato,
  Printer,
  Rabbit,
  Radish,
  Rat,
  Recycle,
  Rocket,
  Ruler,
  Salad,
  Sandwich,
  Scale,
  Scissors,
  Scroll,
  Screwdriver,
  ScreenShare,
  Settings,
  Shark,
  Sheep,
  Shirt,
  Shovel,
  ShowerHead,
  Shrimp,
  Snail,
  Snake,
  Snowflake,
  Sofa,
  Soup,
  SoySauce,
  Sparkles,
  Speaker,
  Spider,
  Sponge,
  Sprout,
  Squash,
  Squirrel,
  Stairs,
  StickyNote,
  Store,
  Sun,
  Swan,
  Syringe,
  Table,
  Tag,
  Tent,
  Thermometer,
  Ticket,
  Torus,
  Towel,
  ToyBrick,
  Tractor,
  Train,
  Trash2,
  TreePine,
  Trophy,
  Trowel,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Wallet,
  Wand,
  WashingMachine,
  Watch,
  Whale,
  Wheat,
  Wine,
  Wolf,
  Worm,
  Wrench,
  Zap,
  ShoppingBasket,
  ShoppingCart,
} from 'lucide-react';

export const supermarketIcons: { [key: string]: LucideIcon } = {
  'air-vent': AirVent,
  'alarm-clock': AlarmClock,
  apple: Apple,
  archive: Archive,
  armchair: Armchair,
  baby: Baby,
  banana: Banana,
  bath: Bath,
  bean: Bean,
  bed: Bed,
  'bed-double': BedDouble,
  'bed-single': BedSingle,
  beef: Beef,
  beer: Beer,
  bird: Bird,
  blinds: Blinds,
  bone: Bone,
  book: Book,
  bot: Bot,
  box: Box,
  brain: Brain,
  brush: Brush,
  bucket: Bucket,
  bug: Bug,
  bus: Bus,
  butterfly: Butterfly,
  cabbage: Cabbage,
  'cake-slice': CakeSlice,
  camera: Camera,
  camel: Camel,
  candy: Candy,
  'candy-cane': CandyCane,
  car: Car,
  carpet: Carpet,
  carrot: Carrot,
  cat: Cat,
  chair: Chair,
  cheese: Cheese,
  cherry: Cherry,
  citrus: Citrus,
  clover: Clover,
  'coat-hanger': CoatHanger,
  coconut: Coconut,
  coffee: Coffee,
  cog: Cog,
  computer: Computer,
  container: Container,
  'cooking-pot': CookingPot,
  cookie: Cookie,
  crane: Crane,
  croissant: Croissant,
  cucumber: Cucumber,
  'cup-soda': CupSoda,
  curtains: Curtains,
  deer: Deer,
  desk: Desk,
  dessert: Dessert,
  dog: Dog,
  dolphin: Dolphin,
  'door-closed': DoorClosed,
  'door-open': DoorOpen,
  dove: Dove,
  drill: Drill,
  droplets: Droplets,
  drumstick: Drumstick,
  egg: Egg,
  'egg-fried': EggFried,
  fan: Fan,
  feather: Feather,
  fence: Fence,
  'fire-extinguisher': FireExtinguisher,
  fish: Fish,
  'fish-symbol': FishSymbol,
  flag: Flag,
  flame: Flame,
  flashlight: Flashlight,
  flower: Flower,
  'flower-2': Flower2,
  forklift: Forklift,
  fox: Fox,
  frog: Frog,
  'frying-pan': FryingPan,
  gamepad: Gamepad,
  gauge: Gauge,
  gem: Gem,
  gift: Gift,
  'glass-water': GlassWater,
  grape: Grape,
  ham: Ham,
  hammer: Hammer,
  'hand-soap': HandSoap,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  horse: Horse,
  'ice-cream': IceCream,
  'ice-cream-2': IceCream2,
  iron: Iron,
  keyboard: Keyboard,
  key: Key,
  ladder: Ladder,
  ladybug: Ladybug,
  lamp: Lamp,
  laptop: Laptop,
  leaf: Leaf,
  lettuce: Lettuce,
  library: Library,
  lightbulb: Lightbulb,
  lock: Lock,
  lollipop: Lollipop,
  mail: Mail,
  map: Map,
  martini: Martini,
  microwave: Microwave,
  milk: Milk,
  monkey: Monkey,
  moon: Moon,
  mop: Mop,
  mouse: Mouse,
  muffin: Muffin,
  notebook: Notebook,
  nut: Nut,
  owl: Owl,
  package: Package,
  'paint-roller': PaintRoller,
  paintbrush: Paintbrush,
  paperclip: Paperclip,
  'parking-circle': ParkingCircle,
  'paw-print': PawPrint,
  pen: Pen,
  pepper: Pepper,
  'person-standing': PersonStanding,
  phone: Phone,
  'picture-in-picture': PictureInPicture,
  'pie-chart': PieChart,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pin: Pin,
  pizza: Pizza,
  plug: Plug,
  'plug-zap': PlugZap,
  plus: Plus,
  popcorn: Popcorn,
  potato: Potato,
  printer: Printer,
  rabbit: Rabbit,
  radish: Radish,
  rat: Rat,
  recycle: Recycle,
  rocket: Rocket,
  ruler: Ruler,
  salad: Salad,
  sandwich: Sandwich,
  scale: Scale,
  scissors: Scissors,
  scroll: Scroll,
  screwdriver: Screwdriver,
  'screen-share': ScreenShare,
  settings: Settings,
  shark: Shark,
  sheep: Sheep,
  shirt: Shirt,
  shovel: Shovel,
  'shower-head': ShowerHead,
  shrimp: Shrimp,
  snail: Snail,
  snake: Snake,
  snowflake: Snowflake,
  sofa: Sofa,
  soup: Soup,
  'soy-sauce': SoySauce,
  sparkles: Sparkles,
  speaker: Speaker,
  spider: Spider,
  sponge: Sponge,
  sprout: Sprout,
  squash: Squash,
  squirrel: Squirrel,
  stairs: Stairs,
  'sticky-note': StickyNote,
  store: Store,
  sun: Sun,
  swan: Swan,
  syringe: Syringe,
  table: Table,
  tag: Tag,
  tent: Tent,
  thermometer: Thermometer,
  ticket: Ticket,
  torus: Torus,
  towel: Towel,
  'toy-brick': ToyBrick,
  tractor: Tractor,
  train: Train,
  'trash-2': Trash2,
  'tree-pine': TreePine,
  trophy: Trophy,
  trowel: Trowel,
  truck: Truck,
  turtle: Turtle,
  tv: Tv,
  umbrella: Umbrella,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  vegan: Vegan,
  wallet: Wallet,
  wand: Wand,
  'washing-machine': WashingMachine,
  watch: Watch,
  whale: Whale,
  wheat: Wheat,
  wine: Wine,
  wolf: Wolf,
  worm: Worm,
  wrench: Wrench,
  zap: Zap,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
};

export const availableSupermarketIcons = Object.keys(supermarketIcons);
